### ISSUE TITLE
Any related paper?

### ISSUE THREAD

**Issue by santteegt** [dice-group/TeBaQA#47]
Hi,

Is there any related paper describing the implementation of this approach, such as the one published in 2015 for HAWK?

**Comment by RicardoUsbeck** [comment]
Hi, there is the master thesis of  @pnancke which is in German. There will soon be a preprint available. I leave this issue open to remind myself to look into this, once done.

**Comment by RicardoUsbeck** [comment]
Dear @santteegt  (@lsiciliani  FYI) 

unfortunately, it took us longer than expected but here is a preprint of how TeBaQA works https://arxiv.org/abs/2103.06752

Best regards
Ricardo
