### ISSUE TITLE
About demo

### ISSUE THREAD

**Issue by xqx1568** [dice-group/TeBaQA#51]
The online service of your demo seems does not work now.
address: https://tebaqa.demos.dice-research.org/
It can not return useful message.
![image](https://user-images.githubusercontent.com/43669838/119217285-c93a2f00-bb0b-11eb-9cea-26e91db11e76.png)
Please check it and tell me what is the problem.
Thanks!

**Comment by RicardoUsbeck** [comment]
Dear @xqx1568 , which request are you sending directly? Best regards, Ricardo

**Comment by tohardik** [comment]
Closing this
