### ISSUE TITLE
Data files for indexing entities

### ISSUE THREAD

**Issue by haophancs** [dice-group/TeBaQA#54]
Hi!
Thank you for sharing your impressive work.
I am trying to reproduce it. Now I have to index entities data to elasticsearch.
I have tried using `mappingbased_objects_en.ttl` from https://downloads.dbpedia.org/2016-10/core/ but still no luck.
There were some `NullPointerException` that occurred at:
- [`nameToProperties_object.put(subject, nameToProperties_object.get(object).append(",,").append(predicate));`](https://github.com/dice-group/TeBaQA/blob/b90befb5e7f6f428443934a3ebe8ea8a9c18fceb/tebaqa-commons/src/main/java/de/uni/leipzig/tebaqa/tebaqacommons/elasticsearch/TripleStatementHandler.java#L65): due to the key `object` was not in `nameToProperties_object`
- Also, [the same problem at line 71](https://github.com/dice-group/TeBaQA/blob/b90befb5e7f6f428443934a3ebe8ea8a9c18fceb/tebaqa-commons/src/main/java/de/uni/leipzig/tebaqa/tebaqacommons/elasticsearch/TripleStatementHandler.java#L71)

I also try catching and passing exceptions. But in the result, there was not an entity item indexed to elasticsearch
I think the problem is caused by incorrect input files, but I still have no idea to get it. I have just started in this kind of task so there may be things I incorrectly did. 
Could you please provide me the input .ttl file?
Thank you,
Hao

**Comment by RicardoUsbeck** [comment]
Dear @haophancs 

we are looking into this issue but the main devs are on vacation. Thank you for your patience in advance.

Best regards
Ricardo

**Comment by haophancs** [comment]
Thank you for your reply!
When you have time, could you please just give me the input .ttl files for indexing entities?
I'll be so appreciative.
Best wishes,
Hao

**Comment by haophancs** [comment]
Hi, so far everything have been working well.
Many thanks for your work!
Best regards,
Hao
